export const PASS_SCORE  = 80
export const TEST_LENGTH = 25
export const ADMIN_PASS  = 'compass2025'

export const DOMAINS = {
  CONSCIOUS: 'What is a Conscious Brand',
  IDENTIFY:  'Identifying Conscious Brands',
  TOOL:      'Using the Tool',
  SCORING:   'How Scores Are Calculated',
  MATURITY:  'Interpreting Scores & Maturity',
  ASSESSOR:  'The Assessor\'s Role',
  ACTION:    'Actioning Insights',
}

export const STUDY_GUIDE = {
  CONSCIOUS: 'Review the Conscious Compass framework deck, particularly the 8-attribute slide and the founding premise that consciousness is measured, not self-proclaimed. Make sure you can describe each of the 8 attributes and the core question behind each one.',
  IDENTIFY:  'Study the "What is a Conscious Brand" reference document. Focus on what strong, moderate and weak evidence looks like for each attribute in practice across website, social, earned media, paid media and trust signals.',
  TOOL:      'Revisit the workflow section of the deck and spend time in the tool itself. Work through a practice assessment from Setup to Score and Export, paying attention to what each step requires and why.',
  SCORING:   'Review the "How the Score is Built" slide carefully. Understand signal tiering, weighting multipliers by business model, and the formula: Rubric + Signals = Raw Score × Weight = Weighted Score → Average of 8 = Final Score.',
  MATURITY:  'Revisit the maturity stage descriptions. Make sure you can describe each stage in your own words, explain what a gap between attributes means strategically, and frame low scores constructively in a client context.',
  ASSESSOR:  'The AI-assisted human intelligence slide is the most important in the entire deck. Revisit it carefully. You need to be able to articulate all four assessor responsibilities — Input Integrity, Score Validation, Brand Expertise and Actionable Insight — and explain why human judgement is irreplaceable in this process.',
  ACTION:    'Review the report output and service recommendation sections. Practise mapping a specific low attribute score to a named Antenna service and making the business case for why it will move the needle.',
}

export const ALL_QUESTIONS = [
  // ── WHAT IS A CONSCIOUS BRAND ────────────────────────────────────────────
  { id:'c1', domain:'CONSCIOUS', q:'Which statement best defines a conscious brand within the Conscious Compass framework?', options:['A brand that invests heavily in sustainability and publishes an annual ESG report that is independently verified','A brand that operates with deliberate awareness and intention across every dimension of its marketing ecosystem','A brand that has achieved formal recognition through industry awards and third-party accreditation bodies','A brand that maintains consistent visual identity and a clearly articulated purpose statement across all channels'], answer:1 },
  { id:'c2', domain:'CONSCIOUS', q:'The framework states that consciousness is not self-proclaimed. What is the practical implication for an assessor?', options:['Assessors must obtain written confirmation from the brand before including any internal claim as evidence','Brands must supply a marketing strategy document before their assessment can be considered valid','Brand consciousness is determined only by what external audiences can publicly observe and verify','Brands are required to share campaign performance data so assessors can validate effectiveness claims'], answer:2 },
  { id:'c3', domain:'CONSCIOUS', q:'Which of the following is NOT one of the 8 attributes assessed by the Conscious Compass?', options:['COGENT','SENTIENT','RESONANT','ATTENTIVE'], answer:2 },
  { id:'c4', domain:'CONSCIOUS', q:'The AWAKE attribute is primarily concerned with which aspect of brand performance?', options:['The emotional resonance a brand creates and its ability to inspire action in target audiences','The quality and consistency of digital experiences the brand delivers across all owned channels','How actively the brand shapes industry narratives and leads discourse in its category','The depth of audience understanding a brand demonstrates through its content and engagement strategy'], answer:2 },
  { id:'c5', domain:'CONSCIOUS', q:'A brand scores 79 on VISIONARY but 31 on INTENTIONAL. What does this gap most likely indicate?', options:['The brand communicates a compelling vision but lacks the professional substance and credibility to support it','The brand is investing in long-term thinking at the expense of tactical campaign delivery and execution','The brand has strong social media performance but is underinvesting in earned media and thought leadership','The brand\'s content strategy is forward-looking but its distribution channels are inconsistently managed'], answer:0 },
  { id:'c6', domain:'CONSCIOUS', q:'The SENTIENT attribute receives a lower weighting for B2B brands. What is the rationale behind this?', options:['B2B brands produce lower quality creative work and are therefore assessed against a reduced standard','B2B purchasing decisions involve longer cycles and more stakeholders where rational evidence carries greater weight','Emotional resonance is considered entirely irrelevant in professional services and B2B categories','B2B brands operate in regulated industries where emotional marketing is restricted by compliance requirements'], answer:1 },
  { id:'c7', domain:'CONSCIOUS', q:'Which attribute asks: \'Do you understand your audiences and build genuine trust with them?\'', options:['REFLECTIVE','ATTENTIVE','AWARE','COGENT'], answer:2 },
  { id:'c8', domain:'CONSCIOUS', q:'What distinguishes a conscious brand from one that simply has a large marketing budget and high spend?', options:['Conscious brands prioritise organic and earned media over paid channels across all markets and categories','Conscious brands operate with awareness and intention — asking why before how, and who before what','Conscious brands have received independent validation from industry bodies for their strategy and execution','Conscious brands make all decisions using quantitative data rather than creative instinct or cultural judgement'], answer:1 },
  { id:'c9', domain:'CONSCIOUS', q:'The REFLECTIVE attribute is best described as which of the following?', options:['The brand\'s capacity to adjust messaging quickly in response to real-time audience feedback and cultural moments','The brand\'s ability to measure and transparently report on marketing performance across all paid channels','The brand\'s clarity of identity and alignment between what it claims externally and how it actually presents itself','The brand\'s willingness to acknowledge public mistakes and communicate openly with all its stakeholders'], answer:2 },
  { id:'c10', domain:'CONSCIOUS', q:'Which of the following is the most accurate description of the COGENT attribute?', options:['The brand produces persuasive and logically structured content that clearly communicates its value proposition','The brand makes intelligent evidence-based decisions informed by data, measurement and strategic thinking','The brand communicates with authority and precision using expert language appropriate to its professional audience','The brand has a sophisticated paid media operation with strong targeting, creative testing and conversion tracking'], answer:1 },

  // ── IDENTIFYING CONSCIOUS BRANDS ─────────────────────────────────────────
  { id:'i1', domain:'IDENTIFY', q:'A technology brand\'s CEO is regularly quoted in tier-1 industry publications, delivers keynotes at major conferences, and publishes original research that analysts and competitors cite. Which attribute does this most strongly evidence?', options:['INTENTIONAL — the brand demonstrates professional credibility through consistent external presentation','COGENT — the brand uses data and strategic insight to inform its marketing decisions','AWAKE — the brand leads industry discourse and proactively shapes narratives in its category','VISIONARY — the brand articulates a forward-looking perspective on the future of its industry'], answer:2 },
  { id:'i2', domain:'IDENTIFY', q:'A brand\'s website scores 94 on PageSpeed, meets WCAG 2.1 AA accessibility standards, uses professional photography throughout, and features clear logical conversion paths. Which attribute is most evidenced?', options:['REFLECTIVE — consistent and high-quality visual presentation across all owned digital touchpoints','COGENT — data-driven optimisation of the brand\'s primary digital channel and user experience','INTENTIONAL — the brand operates with deliberate professionalism and attention to detail throughout','ATTENTIVE — the brand delivers a carefully considered and quality digital experience for its audiences'], answer:3 },
  { id:'i3', domain:'IDENTIFY', q:'A brand\'s social media uses distinctive visual identity rather than stock imagery, tells genuine customer stories, and consistently generates emotional responses and meaningful conversation. Which attribute does this most directly demonstrate?', options:['SENTIENT — the brand creates emotional resonance and distinctive creative work that connects with its audience','AWARE — the brand demonstrates deep audience understanding through platform-appropriate content strategy','AWAKE — the brand shapes industry conversation through a compelling social media presence','REFLECTIVE — the brand maintains a consistent and recognisable expression across all social channels'], answer:0 },
  { id:'i4', domain:'IDENTIFY', q:'A professional services firm leads its About page with a clear purpose beyond commercial goals, publishes content addressing the future of its sector, and its leadership team takes public positions on relevant industry issues. Which attribute is most evidenced?', options:['AWAKE — the brand is shaping narratives and actively leading industry discourse in its category','INTENTIONAL — the brand demonstrates professional substance and consistent credibility across channels','REFLECTIVE — the brand has a clear and authentic identity that it expresses consistently','VISIONARY — the brand stands for something meaningful and looks beyond immediate commercial activity'], answer:3 },
  { id:'i5', domain:'IDENTIFY', q:'A brand\'s case studies include specific metrics and outcomes, its paid media shows clear audience segmentation, and its content visibly addresses real search intent rather than generic topics. Which attribute is most evidenced?', options:['ATTENTIVE — the brand applies careful attention to detail across all its marketing execution','COGENT — the brand makes intelligent evidence-based decisions and demonstrates a visible measurement culture','INTENTIONAL — the brand operates with deliberate discipline and professional consistency throughout','AWAKE — the brand leads category thinking through data-informed and well-evidenced thought leadership'], answer:1 },
  { id:'i6', domain:'IDENTIFY', q:'A brand\'s Glassdoor reviews consistently reflect its external values, employees post authentically about their work, and its internal culture visibly matches its public brand positioning. Which attribute does this most strongly support?', options:['INTENTIONAL — the brand presents with professional credibility and consistency across all external contexts','ATTENTIVE — the brand\'s quality standards extend meaningfully to the internal employee experience','AWARE — the brand demonstrates understanding of multiple audiences including its own employee base','REFLECTIVE — the brand\'s internal reality is genuinely aligned with its external identity and positioning'], answer:3 },
  { id:'i7', domain:'IDENTIFY', q:'A brand is active on LinkedIn and Instagram with high-quality well-targeted content, but has no presence on X or TikTok. How should this be assessed?', options:['As a WEAK signal — a fully conscious brand maintains active and consistent presence across all major platforms','As a MODERATE signal — presence on only two platforms indicates an incomplete and underdeveloped social strategy','As a STRONG signal — selective high-quality presence on the right platforms outperforms shallow presence everywhere','As excluded from scoring — platform selection decisions are outside the scope of the Compass framework'], answer:2 },
  { id:'i8', domain:'IDENTIFY', q:'A brand has a beautifully designed homepage but three broken links in the footer, inconsistent logo usage across social profiles, and an expired SSL certificate on a legacy subdomain. How does this affect scoring?', options:['These are minor cosmetic errors and would not materially affect any attribute score in the assessment','These issues are relevant only to COGENT as they reflect poor technical decision-making and oversight','These create WEAK signals across ATTENTIVE and INTENTIONAL — attention to detail matters at every level','These would only affect scoring if the brand is in the Establishing maturity stage or below'], answer:2 },
  { id:'i9', domain:'IDENTIFY', q:'A B2C lifestyle brand produces highly distinctive campaigns that generate significant cultural conversation, but its PageSpeed score is 41 and its paid media targeting is broad and unfocused. What does this profile suggest?', options:['Strong SENTIENT signals paired with WEAK signals on ATTENTIVE and COGENT — creative strength without operational discipline','Strong AWAKE signals indicating effective narrative leadership offset by WEAK REFLECTIVE consistency','A brand in the Differentiating stage whose investment is correctly focused on brand-building over performance marketing','Strong VISIONARY signals reflecting purpose-led strategy not yet reflected in technical and paid execution'], answer:0 },
  { id:'i10', domain:'IDENTIFY', q:'A brand has a Wikipedia page with 14 external citations, registered trademarks in multiple territories, displays client logos and certifications prominently, and maintains professional brand standards across every touchpoint. Which attribute is most strongly evidenced?', options:['AWAKE — third-party validation and recognition signal strong narrative leadership in the brand\'s category','COGENT — trademark registration and credential management reflect data-driven strategic decision-making','AWARE — the brand demonstrates understanding of the signals its professional audiences use to build trust','INTENTIONAL — the brand operates with deliberate professionalism and credible substance throughout'], answer:3 },
  { id:'i11', domain:'IDENTIFY', q:'A brand\'s 90-day earned coverage includes features in two tier-1 publications, a CEO podcast appearance as the invited expert, and an analyst report citing their proprietary research. No press releases were issued in the same period. What does this indicate?', options:['A WEAK earned media profile because no active PR programme was in place to generate and drive the coverage','A MODERATE profile — tier-1 coverage is positive but the absence of press releases limits consistency and control','Strong AWAKE signals — the brand is being sought out as an authority not merely covered as a subject of news','Strong INTENTIONAL signals — the quality of external recognition reflects the brand\'s professional credibility'], answer:2 },
  { id:'i12', domain:'IDENTIFY', q:'A brand\'s LinkedIn is authored by its marketing team, uses stock imagery throughout, posts at consistent frequency, but generates minimal engagement and receives virtually no comments. How should this be assessed?', options:['As a STRONG signal — consistent posting frequency demonstrates a disciplined and well-managed content programme','As a MODERATE signal — the brand is present and active but lacks genuine audience connection and resonance','As a STRONG AWARE signal — maintaining consistent cadence shows an audience-focused and planned approach','As excluded from scoring — engagement metrics fluctuate with platform algorithms and cannot be reliably assessed'], answer:1 },
  { id:'i13', domain:'IDENTIFY', q:'A brand\'s paid media runs identical creative across Meta, LinkedIn and programmatic display with no audience customisation or channel-specific adaptation. Which attribute does this most directly reflect weakness in?', options:['SENTIENT — the brand is failing to create the emotional resonance required for effective creative performance','ATTENTIVE — the brand is not paying sufficient attention to the quality of individual channel experiences','COGENT — the brand is not applying strategic intelligence or evidence to inform its paid media decisions','AWARE — the brand does not demonstrate sufficient understanding of how different audiences use different channels'], answer:2 },
  { id:'i14', domain:'IDENTIFY', q:'A brand\'s About page leads with founding date, company headcount, and a list of services. There is no purpose statement, no articulation of why the company exists, and no forward-looking vision content anywhere on the site. Which attribute is most clearly signalled as WEAK?', options:['REFLECTIVE — the brand has not established a clear and distinctive identity that differentiates it from competitors','INTENTIONAL — the brand lacks the professional credibility signals that build trust with prospective clients','VISIONARY — the brand shows no evidence of standing for something meaningful beyond its commercial activity','COGENT — the brand is not applying strategic thinking to the structure and purpose of its owned digital content'], answer:2 },

  // ── USING THE TOOL ───────────────────────────────────────────────────────
  { id:'t1', domain:'TOOL', q:'What are the six workflow steps of the Conscious Compass assessment in the correct sequence?', options:['Setup, Social and Paid, Website, AI Reputation, Earned Media, Score and Export','Setup, Website, Social and Paid, AI Reputation, Earned Media, Score and Export','Setup, Earned Media, Website, Social and Paid, AI Reputation, Score and Export','Brief, Website, Social and Paid, Earned Media, AI Reputation, Score and Export'], answer:1 },
  { id:'t2', domain:'TOOL', q:'What four pieces of information are entered during the Setup step of the assessment?', options:['Brand name, target audience definition, primary competitors, and campaign objectives','Brand name, founding date, primary industry vertical, and annual marketing investment','Brand name, website URL, industry, and business model (B2B, B2C or B2B2C)','Brand name, social media handles, primary markets served, and number of employees'], answer:2 },
  { id:'t3', domain:'TOOL', q:'How is AI Reputation data gathered and entered into the Conscious Compass?', options:['The tool queries Claude, Gemini and ChatGPT automatically via integrated API connections in the background','The assessor uses a standardised prompt and manually pastes each platform\'s response into the relevant tool field','The brand provides a self-assessment of how it believes each AI platform describes and evaluates it','AI reputation is inferred from the brand\'s organic search performance and domain authority signals'], answer:1 },
  { id:'t4', domain:'TOOL', q:'Why is entering the correct business model during Setup important for the accuracy of the assessment?', options:['It determines which subset of the 8 attributes are included in the assessment for that specific brand type','It selects the appropriate report template and determines which export formats are made available','It applies the correct weighting multipliers that calibrate attribute scores for the brand\'s commercial context','It adjusts the pass threshold used to determine which maturity stage the brand is assigned to'], answer:2 },
  { id:'t5', domain:'TOOL', q:'What does the ability to rescore saved assessments enable for assessors and clients?', options:['It allows assessors to revise scores downward after receiving client pushback on the initial results','It allows the same evidence base to be re-evaluated against an updated framework for fair comparison over time','It enables two assessors to independently score the same brand and automatically reconcile their differences','It allows scores to update automatically when new content is published by the brand being assessed'], answer:1 },
  { id:'t6', domain:'TOOL', q:'Which data sources are assessed as part of the Trust Signals section of the Compass?', options:['Google Reviews, Trustpilot, Capterra ratings, and customer satisfaction survey results','Glassdoor, Wikipedia, WIPO trademark data, and influencer and creator partnerships','LinkedIn recommendations, client testimonials, industry awards databases, and NPS scores','Press archives, analyst reports, investor relations pages, and professional certification bodies'], answer:1 },
  { id:'t7', domain:'TOOL', q:'Approximately how long should a thorough Conscious Compass assessment take from Setup to Score and Export?', options:['10 to 20 minutes, with the AI handling the majority of evidence gathering automatically','30 to 50 minutes, with progress auto-saved at every step throughout the assessment','1 to 2 hours, depending on the depth and breadth of evidence available for the brand','Half a working day, to allow adequate time for research, verification and score validation'], answer:1 },

  // ── SCORING ──────────────────────────────────────────────────────────────
  { id:'s1', domain:'SCORING', q:'What are the three mechanisms that combine to produce each attribute score in the Conscious Compass?', options:['Evidence Gathering, AI Analysis, and Human Validation and Review','Research, Classification, and Industry Benchmarking','The Rubric, Signal Tiering, and Business Model Weighting','Observation, Scoring, and Assessor Calibration'], answer:2 },
  { id:'s2', domain:'SCORING', q:'A B2B brand has a raw COGENT score of 60. The B2B multiplier for COGENT is ×1.25. What is the correct weighted score?', options:['60.0 — weighting multipliers only apply to scores below the 50-point midpoint threshold','72.0 — the multiplier adds 20% of the raw score to the original figure','75.0 — the raw score is multiplied directly by the weighting factor','78.5 — the multiplier applies to the gap between the raw score and the maximum'], answer:2 },
  { id:'s3', domain:'SCORING', q:'An assessor finds no evidence of a brand having a Wikipedia page or any third-party knowledge panel. How should this absence be treated?', options:['As a neutral finding — Wikipedia is optional and its absence does not affect any attribute score','As a WEAK or absent signal that negatively affects the relevant attribute score, since absent evidence is not neutral','As a data gap that should be flagged in the report and excluded from the final score calculation','As a MODERATE signal — absence of Wikipedia presence is common enough that brands are not penalised for it'], answer:1 },
  { id:'s4', domain:'SCORING', q:'How is the overall Conscious Compass score calculated from the 8 individual attribute scores?', options:['The single highest weighted attribute score is used as the overall score to reflect the brand\'s peak performance','The three lowest weighted attribute scores are averaged to identify the area most requiring strategic attention','The average of all 8 weighted attribute scores is calculated and rounded to the nearest whole number','Attribute scores are summed and divided by the maximum possible total to produce a normalised percentage'], answer:2 },
  { id:'s5', domain:'SCORING', q:'Which of the following correctly describes a STRONG signal within the Compass rubric?', options:['Evidence that appears across more than three separate channels or sources simultaneously','Evidence that is present but inconsistently applied or only partially demonstrated across touchpoints','Evidence that unambiguously and consistently demonstrates the attribute being assessed','Evidence sourced from owned channels such as the brand\'s website or published case studies'], answer:2 },
  { id:'s6', domain:'SCORING', q:'The Compass rubric contains how many distinct signal criteria across all 8 attributes?', options:['24 — three clearly defined signal criteria per attribute at each tier level','40 — five distinct signal criteria assessed for every attribute','50 — the full set of criteria in the proprietary rubric','64 — eight signal criteria assessed independently per attribute'], answer:2 },
  { id:'s7', domain:'SCORING', q:'What does Signal Tiering mean within the Conscious Compass scoring framework?', options:['Ranking each data source by its credibility and reliability before including it in the assessment','Organising brands into performance tiers based on their overall Compass score and maturity stage','Classifying each piece of gathered evidence as Strong, Moderate or Weak against the rubric criteria','Weighting different social platforms differently based on their relevance to the brand\'s business model'], answer:2 },

  // ── MATURITY ─────────────────────────────────────────────────────────────
  { id:'m1', domain:'MATURITY', q:'A brand scores 67 overall on the Conscious Compass. Which maturity stage does this place them in?', options:['Establishing — the brand is beginning to develop intentional and consistent presence across channels','Differentiating — the brand is standing out intentionally and consistently from its competitors','Leading — the brand is actively shaping industry narratives and setting standards for others','Transforming — the brand defines the category and others actively aspire to emulate its approach'], answer:1 },
  { id:'m2', domain:'MATURITY', q:'A brand has a strong overall score of 74 but REFLECTIVE scores only 38. What is the most strategically significant interpretation?', options:['The low REFLECTIVE score is an anomaly that should be disregarded given the strength of the overall profile','The brand should be reclassified into a lower maturity stage to account for the significant attribute gap','The gap represents a specific strategic vulnerability that could undermine the brand\'s overall strength if left unaddressed','The assessor should rerun the assessment to verify whether the low score reflects a data gap or genuine weakness'], answer:2 },
  { id:'m3', domain:'MATURITY', q:'What does the spider chart in a Compass report enable an assessor to communicate at a glance?', options:['A direct comparison between the assessed brand and the industry benchmark for each of the 8 attributes','A visual overview of all 8 attribute scores simultaneously revealing the brand\'s shape, strengths and gaps','The historical trend of each attribute score across multiple previous assessment periods','The relative weighting applied to each attribute for the brand\'s specific business model'], answer:1 },
  { id:'m4', domain:'MATURITY', q:'A brand is in the Pre-Foundational stage (0–25). How should an assessor frame this finding in a client conversation?', options:['As a crisis requiring immediate remediation before any other marketing activity is undertaken','As a baseline that creates a clear evidence-based starting point and a roadmap for exactly where to begin','As likely inaccurate, suggesting incomplete evidence was gathered and the assessment should be repeated','As a position that is common for brands of this size and therefore should not be a cause for concern'], answer:1 },
  { id:'m5', domain:'MATURITY', q:'What is the strategic value of running the Conscious Compass on the same brand at intervals over time?', options:['It ensures the rubric is applied consistently when multiple assessors work on the same client','It generates a larger data set that improves the accuracy of the AI\'s scoring methodology over time','It enables tracking of brand improvement and direct measurement of the impact of strategic actions taken','It satisfies a contractual requirement that Compass assessments must be formally renewed on an annual basis'], answer:2 },
  { id:'m6', domain:'MATURITY', q:'What does evidence-based scoring mean in the context of a Compass report delivered to a client?', options:['The scoring methodology is grounded in peer-reviewed academic research and validated marketing science','Every attribute score references the specific publicly observable inputs used, making it auditable and defensible','The brand supplied primary research and internal performance data which underpins the scores generated','Scores are based exclusively on quantitative data with qualitative and contextual assessments excluded'], answer:1 },

  // ── ASSESSOR'S ROLE ──────────────────────────────────────────────────────
  { id:'a1', domain:'ASSESSOR', q:'The Compass is described as \'AI-assisted human intelligence\'. What is the most accurate description of the assessor\'s role?', options:['The assessor enters data into the tool and the AI independently determines the scores and all recommendations','The assessor is the quality layer — ensuring evidence integrity, validating outputs, applying expertise, and turning scores into strategy','The assessor\'s primary role is to present and explain the AI\'s output to clients in a clear and accessible way','The assessor reviews the AI-generated report and adjusts any scores where client relationships require sensitivity'], answer:1 },
  { id:'a2', domain:'ASSESSOR', q:'What does Input Integrity require of the assessor when building the evidence base for an assessment?', options:['That all evidence is entered into the correct tool field and cross-referenced with at least two independent sources','That all evidence is gathered within a defined time window to ensure currency and prevent outdated material being used','That the evidence is honest, complete and representative — including flagging gaps rather than simply omitting them','That the assessor obtains written permission from the brand before including any third-party source material'], answer:2 },
  { id:'a3', domain:'ASSESSOR', q:'A brand\'s ATTENTIVE score returns at 77. The assessor has personally observed that the brand\'s mobile experience has broken navigation on three key conversion pages. What should the assessor do?', options:['Accept the score — the AI evaluated the same evidence base and 77 reflects the overall balance of signals','Flag the discrepancy as a caveat in the report but leave the score unchanged to preserve methodological objectivity','Challenge the score, surface the specific mobile evidence, and adjust the score if the evidence warrants it','Request that the client\'s account lead review the finding before it is included in the final report'], answer:2 },
  { id:'a4', domain:'ASSESSOR', q:'A client disputes their AWARE score of 43, saying \'we know our audiences better than any external tool can measure\'. What is the most effective assessor response?', options:['Offer to rescore the assessment with the client present to ensure their perspective is fully reflected in the output','Acknowledge their view then reference the specific observable evidence that produced the score and explain what stronger signals would look like','Agree that audience understanding is inherently difficult to assess externally and note this as a known limitation','Defer the conversation to a senior Antenna account director before providing any formal response'], answer:1 },
  { id:'a5', domain:'ASSESSOR', q:'Why is cherry-picking evidence — selecting only the brand\'s strongest examples — a serious problem in a Compass assessment?', options:['It significantly increases assessment time by requiring more evidence items per attribute than the rubric specifies','It is technically detectable by the AI engine and will trigger an automatic recalibration of the scores','It produces inflated scores that mislead the client about their actual brand position and lead to misdirected investment','It risks including privately held evidence that falls outside the publicly observable scope of the framework'], answer:2 },
  { id:'a6', domain:'ASSESSOR', q:'A client asks why the Compass only looks at publicly available information rather than accessing internal brand data. What is the most accurate and compelling response?', options:['Internal data is too commercially sensitive to include and would create a conflict of interest for the assessing party','The framework focuses on public information because that is how the brand is actually experienced, judged and chosen','Internal data is too difficult to standardise across different brands and sectors and would undermine comparability','Future versions of the Compass will incorporate internal data but the current methodology is limited to public sources'], answer:1 },
  { id:'a7', domain:'ASSESSOR', q:'What does Brand Expertise mean as the third component of the assessor\'s responsibility?', options:['The ability to complete a full Compass assessment within the recommended 30–50 minute timeframe','Having worked directly on the client brand for a minimum qualifying period before conducting the assessment','Applying sector knowledge and brand best practice to interpret scores in context and explain their strategic meaning','Holding a recognised professional certification in brand strategy before being permitted to use the tool'], answer:2 },
  { id:'a8', domain:'ASSESSOR', q:'The framework states the Compass \'is only as good as the expertise and integrity of the person using it\'. What is the primary implication?', options:['The tool should be restricted to senior strategists with a minimum of ten years of brand and marketing experience','Every Compass assessment should be independently peer-reviewed before being shared with any client','The quality of the output directly reflects the assessor — their rigour, honesty and expertise shape the entire result','The tool is in active development and should only be used with clients who understand its current limitations'], answer:2 },
  { id:'a9', domain:'ASSESSOR', q:'What does Actionable Insight — the fourth assessor responsibility — require beyond delivering the report?', options:['Ensuring all PDF and DOCX report files are correctly formatted and error-free before they are sent to the client','Sending a follow-up summary email to the client within 24 hours of the assessment session being completed','Using insights, themes and recommendations to help shape brand, campaign and integrated marketing strategies','Following up at three and six months to measure and report on whether the brand\'s scores have since improved'], answer:2 },

  // ── ACTIONING INSIGHTS ───────────────────────────────────────────────────
  { id:'ac1', domain:'ACTION', q:'How does the Compass translate low attribute scores into specific Antenna service recommendations?', options:['The assessor selects relevant services manually from the Antenna catalogue based on their own professional judgement','The tool\'s service mapping layer automatically connects low-scoring attributes to the most relevant Antenna services','A senior Antenna strategist reviews the completed report and generates recommendations independently afterwards','Clients select from a pre-defined set of service packages linked to their overall maturity stage in the framework'], answer:1 },
  { id:'ac2', domain:'ACTION', q:'A brand scores 36 on REFLECTIVE. What type of Antenna service is most likely to be recommended and why?', options:['Paid media services — to increase visibility and commercial performance while identity issues are being resolved','SEO and performance marketing — to improve findability and drive inbound traffic to the brand\'s digital channels','Brand Strategy and Expression — to address the foundational gaps in authenticity, clarity and consistent identity','Social media management — to establish a more consistent and recognisable brand voice across active platforms'], answer:2 },
  { id:'ac3', domain:'ACTION', q:'Why does the recommendation logic prioritise the lowest-scoring attributes rather than reinforcing the strongest ones?', options:['High-scoring attributes are typically managed by specialist agencies and cannot practically be improved further','Addressing the lowest scores has the greatest impact on the overall Compass score and closes the brand\'s key strategic gaps','Clients are more receptive to investing in areas where they know their brand is visibly underperforming','The rubric assigns greater inherent commercial value to foundational attributes which are more likely to score low'], answer:1 },
  { id:'ac4', domain:'ACTION', q:'A client\'s COGENT score is 41. They respond: \'we don\'t do thought leadership\'. How should the assessor make the business case?', options:['Agree that thought leadership may not suit their sector and refocus recommendations on higher-scoring attributes','Present competitor COGENT scores and allow the comparative market position data to speak for itself','Frame COGENT as data-driven intelligence — connecting it to buyer confidence, credibility and the quality of decisions','Recommend a content audit as a low-risk first step before committing to a broader COGENT improvement programme'], answer:2 },
  { id:'ac5', domain:'ACTION', q:'When presenting service recommendations to a client, what is the assessor\'s most important responsibility?', options:['Ensuring the full breadth of the Antenna service offering is presented so the client understands all available support','Recommending the highest-value services first to maximise the commercial opportunity generated by the assessment','Connecting every recommendation explicitly to the evidence and score so the client understands why it will move the needle','Limiting recommendations to no more than three services to avoid overwhelming the client with options and decisions'], answer:2 },
  { id:'ac6', domain:'ACTION', q:'A brand has had three Compass assessments over 18 months. Their ATTENTIVE score has improved from 40 to 69. How is this most effectively used?', options:['As confirmation the ATTENTIVE gap is fully resolved and resources should now be redirected to other lower attributes','As evidence that the Compass framework is producing accurate scores and further investment in the tool is justified','As measurable proof of impact that validates investment, informs the next phase of work, and strengthens the relationship','As a case study to be published publicly demonstrating Antenna\'s effectiveness at improving brand performance'], answer:2 },
  { id:'ac7', domain:'ACTION', q:'The benchmark and comparison view in the Compass provides what specific commercial value for Antenna as an agency?', options:['It allows Antenna to set service pricing based on a brand\'s relative performance against its competitive set','It provides cross-brand intelligence that informs sector-level strategic narratives, proposals and thought leadership','It automatically generates competitive analysis reports that can be delivered directly to prospective new clients','It validates the accuracy of individual assessments by cross-checking scores against verified category averages'], answer:1 },
]

export function shuffle(a) {
  const b = [...a]
  for (let i = b.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [b[i], b[j]] = [b[j], b[i]]
  }
  return b
}

export function buildTest() {
  const byD = {}
  Object.keys(DOMAINS).forEach(d => { byD[d] = shuffle(ALL_QUESTIONS.filter(q => q.domain === d)) })
  const min = { ASSESSOR:4, IDENTIFY:4, CONSCIOUS:2, TOOL:2, SCORING:2, MATURITY:2, ACTION:2 }
  let sel = []
  Object.entries(min).forEach(([d, n]) => sel.push(...(byD[d]||[]).slice(0, n)))
  const rest = shuffle(Object.entries(min).flatMap(([d, n]) => (byD[d]||[]).slice(n)))
  sel.push(...rest.slice(0, TEST_LENGTH - sel.length))
  return shuffle(sel)
}

export function getStudyRecs(answers) {
  return Object.keys(DOMAINS)
    .filter(d => {
      const qs = answers.filter(a => a.domain === d)
      return qs.length > 0 && qs.filter(a => a.correct).length / qs.length < 0.75
    })
    .map(d => ({ domain: DOMAINS[d], guidance: STUDY_GUIDE[d] }))
}

export function fmt(s) {
  return `${String(Math.floor(s / 60)).padStart(2,'0')}:${String(s % 60).padStart(2,'0')}`
}
